-- FUNCION QUE COMPRUEBA SI EL EMPLEADO TIENE EL PUESTO INDICADO, DEVUELVE NULL SI NO EXISTE ESE EMPLEADO
CREATE OR REPLACE FUNCTION compruebaPuesto (NUMEMPLEADO NUMBER, PUESTOEMPLEADO VARCHAR2) RETURN BOOLEAN IS
	EMPLE NUMBER(1);
	EMPLEPUESTO NUMBER(1);
BEGIN
	SELECT COUNT(*) INTO EMPLE FROM EMPLEADO WHERE NUM_EMP=NUMEMPLEADO;
	IF EMPLE=0 THEN
		RETURN NULL;
	ELSE
		SELECT COUNT(*) INTO EMPLEPUESTO FROM EMPLEADO WHERE NUM_EMP=NUMEMPLEADO AND UPPER(PUESTOEMPLEADO)=UPPER(PUESTO);
		IF EMPLEPUESTO=0 THEN
			RETURN FALSE;
		ELSE
			RETURN TRUE;
		END IF;
	END IF;
END;
/